# Generated by Django 3.1.3 on 2020-11-05 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptionalWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefixe', models.CharField(max_length=50, verbose_name='Préfixe')),
                ('suffixe', models.CharField(max_length=50, verbose_name='Suffixe')),
                ('stem', models.CharField(max_length=50, verbose_name='Racine')),
                ('etype', models.CharField(max_length=50, verbose_name='Type')),
                ('voweled_form', models.CharField(max_length=50, verbose_name='Forme voyéllée')),
                ('unvoweled_form', models.CharField(max_length=50, verbose_name='Forme non voyéllée')),
            ],
            options={
                'verbose_name': 'ExceptionnalWord',
                'verbose_name_plural': 'ExceptionnalWords',
            },
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voweled_form', models.CharField(max_length=50, verbose_name='Forme voyéllée')),
                ('ptype', models.CharField(max_length=50, verbose_name='Type')),
                ('ntype', models.CharField(max_length=50, null=True, verbose_name='Sous type nominal')),
                ('vtype', models.CharField(max_length=50, null=True, verbose_name='Sous type verbal')),
                ('broken_plural', models.BooleanField(verbose_name='جمع تكسير')),
                ('comment', models.CharField(max_length=50, verbose_name='Commentaire')),
            ],
            options={
                'verbose_name': 'Pattern',
                'verbose_name_plural': 'Patterns',
            },
        ),
        migrations.CreateModel(
            name='Prefixe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(max_length=2, verbose_name='Classe')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
                ('voweled_form', models.CharField(max_length=50, verbose_name='Forme voyéllé')),
                ('unvoweled_form', models.CharField(max_length=50, verbose_name='Forme non voyéllé')),
            ],
            options={
                'verbose_name': 'Préfixe',
                'verbose_name_plural': 'Préfixe',
            },
        ),
        migrations.CreateModel(
            name='ProperNoun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptype', models.CharField(max_length=50, verbose_name='Type')),
                ('voweled_form', models.CharField(max_length=50, verbose_name='Forme voyéllé')),
                ('unvoweled_form', models.CharField(max_length=50, verbose_name='Forme non voyéllé')),
            ],
            options={
                'verbose_name': 'Nom propre',
                'verbose_name_plural': 'Noms propres',
            },
        ),
        migrations.CreateModel(
            name='Racine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unvoweled_form', models.CharField(max_length=50, verbose_name='Forme non voyéllée')),
            ],
            options={
                'verbose_name': 'Racine',
                'verbose_name_plural': 'Racines',
            },
        ),
        migrations.CreateModel(
            name='Suffixe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(max_length=2, verbose_name='Classe')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
                ('voweled_form', models.CharField(max_length=50, verbose_name='Forme voyéllé')),
                ('unvoweled_form', models.CharField(max_length=50, verbose_name='Forme non voyéllé')),
            ],
            options={
                'verbose_name': 'Suffixe',
                'verbose_name_plural': 'Suffixes',
            },
        ),
        migrations.CreateModel(
            name='ToolWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(verbose_name='Priorité')),
                ('prefixe_class', models.CharField(max_length=50, verbose_name='Classe du préfixe')),
                ('suffixe_class', models.CharField(max_length=50, verbose_name='Classe du suffixe')),
                ('ttype', models.CharField(max_length=50, verbose_name='Type du mot outil')),
                ('voweled_form', models.CharField(max_length=50, verbose_name='Forme voyéllée')),
            ],
            options={
                'verbose_name': 'ToolWord',
                'verbose_name_plural': 'ToolWords',
            },
        ),
    ]
