# Generated by Django 3.1.3 on 2020-11-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irib', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='unvoweled_form',
            field=models.CharField(default=0, max_length=50, verbose_name='Forme non voyéllée'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toolword',
            name='unvoweled_form',
            field=models.CharField(default=0, max_length=50, verbose_name='Forme non voyéllée'),
            preserve_default=False,
        ),
    ]
