# Generated by Django 3.1.3 on 2020-11-23 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('irib', '0002_auto_20201107_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='RulePack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name="Nom de l'ensemble")),
                ('active', models.BooleanField(verbose_name="Activité de l'ensemble")),
            ],
            options={
                'verbose_name': 'Ensemble de régles',
                'verbose_name_plural': 'Ensembles de régles',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Libelé')),
                ('is_start', models.BooleanField(verbose_name="Possibilité d'un départ")),
                ('is_end', models.BooleanField(verbose_name='Possibilité de fin')),
                ('rule_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irib.rulepack', verbose_name='Ensemble de régles')),
            ],
            options={
                'verbose_name': 'Etat',
                'verbose_name_plural': 'Etats',
            },
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_type', models.CharField(choices=[('nom', 'إسم'), ('verb', 'فعل'), ('tool', 'أداة')], max_length=20, null=True, verbose_name='نوع الكلمة')),
                ('word_subtype', models.CharField(choices=[('nom', 'إسم'), ('verb', 'فعل'), ('tool', 'أداة')], max_length=20, null=True, verbose_name='تكمبل نوع الكلمة')),
                ('halat_al_irab', models.CharField(choices=[('raf3', 'رفع'), ('nasb', 'نصب'), ('jarr', 'جر'), ('jazm', 'جزم')], max_length=20, null=True, verbose_name='حالة الإعراب')),
                ('is_muaaraf', models.BooleanField(null=True, verbose_name='معرف')),
                ('active', models.BooleanField(verbose_name='Activité de la transition')),
                ('from_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next', to='irib.state', verbose_name='Etat de provenance')),
                ('rule_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irib.rulepack', verbose_name='Ensemble de régles')),
                ('to_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prev', to='irib.state', verbose_name='Etat de destination')),
            ],
            options={
                'verbose_name': 'Transition',
                'verbose_name_plural': 'Transitions',
            },
        ),
    ]
