# Generated by Django 3.1.3 on 2020-11-24 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('irib', '0003_rulepack_state_transition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transition',
            name='from_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nexts', to='irib.state', verbose_name='Etat de provenance'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='to_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prevs', to='irib.state', verbose_name='Etat de destination'),
        ),
    ]
