# Generated by Django 3.1.3 on 2020-11-26 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irib', '0006_auto_20201124_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transition',
            name='word_subtype',
            field=models.CharField(max_length=20, null=True, verbose_name='تكمبل نوع الكلمة'),
        ),
    ]
