# Generated by Django 3.1.3 on 2020-11-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irib', '0007_auto_20201127_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='active',
            field=models.BooleanField(default=True, verbose_name="Activité de l'état"),
        ),
        migrations.AlterField(
            model_name='transition',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activité de la transition'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='halat_al_irab',
            field=models.CharField(choices=[('raf3', 'رفع'), ('nasb', 'نصب'), ('jarr', 'جر'), ('jazm', 'جزم')], max_length=20, null=True, verbose_name='حالة الإعراب'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='word_subtype',
            field=models.CharField(choices=[('adjectival', 'صفة'), ('nominal', 'إسم'), ('nominal/adjectival', 'إسم - صفة'), ('participial', 'مكون من إسم الفاعل أو المفعول'), ('1', 'فعل من الشكل 1'), ('2', 'فعل من الشكل 2'), ('3', 'فعل من الشكل 3'), ('4', 'فعل من الشكل 4'), ('5', 'فعل من الشكل 5'), ('6', 'فعل من الشكل 6'), ('7', 'فعل من الشكل 7'), ('8', 'فعل من الشكل 8'), ('9', 'فعل من الشكل 9'), ('present', 'فعل مضارع'), ('unclassified', 'unclassified')], max_length=40, null=True, verbose_name='تكمبل نوع الكلمة'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='word_type',
            field=models.CharField(choices=[('nominal', 'إسم'), ('verbs', 'فعل'), ('tool', 'أداة'), ('Comparative', 'مقارنة'), ('Masdar', 'مصدر'), ('Miscellaneous', 'متنوع'), ('active_participle', 'نعت'), ('artificial_masdar', 'مصدر صناعي'), ('brokenPlural', 'جمع التكسير'), ('instrument', 'إسم أداة'), ('marrah', 'إسم مرة'), ('mubalagah', 'مبالغة'), ('mushabbaha', 'مشبهة'), ('nisbah', 'نسبة'), ('passive_participle', 'النعت السلبي'), ('place', 'إسم مكان'), ('regular_feminine_dual', 'مثنى مؤنث'), ('singular_forms-broken_plural_forms', 'إسم مفرد'), ('singular_forms-fem_plural_forms', 'إسم مؤنث'), ('singular_forms-no_plural_forms', '...'), ('singular_forms-reg_plural_forms', '...')], max_length=40, null=True, verbose_name='نوع الكلمة'),
        ),
    ]
