# Generated by Django 3.1.3 on 2020-11-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irib', '0008_auto_20201129_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transition',
            name='word_subtype',
            field=models.CharField(max_length=40, null=True, verbose_name='تكمبل نوع الكلمة'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='word_type',
            field=models.CharField(choices=[('adjectival', 'صفة'), ('nominal', 'إسم'), ('nominal/adjectival', 'إسم - صفة'), ('participial', 'مكون من إسم الفاعل أو المفعول'), ('1', 'فعل من الشكل 1'), ('2', 'فعل من الشكل 2'), ('3', 'فعل من الشكل 3'), ('4', 'فعل من الشكل 4'), ('5', 'فعل من الشكل 5'), ('6', 'فعل من الشكل 6'), ('7', 'فعل من الشكل 7'), ('8', 'فعل من الشكل 8'), ('9', 'فعل من الشكل 9'), ('present', 'فعل مضارع'), ('نسبة إلى اسم علم', 'نسبة إلى اسم علم'), ('اسم علم', 'اسم علم'), ('اسم الجلالة', 'اسم الجلالة')], max_length=40, null=True, verbose_name='نوع الكلمة'),
        ),
    ]
