# Generated by Django 3.1.3 on 2020-11-30 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('irib', '0009_auto_20201130_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transition',
            name='from_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_transitions', to='irib.state', verbose_name='Etat de provenance'),
        ),
    ]
