# Generated by Django 3.1.3 on 2020-12-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irib', '0012_auto_20201201_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='transition',
            name='occ',
            field=models.IntegerField(default=0, verbose_name='Poids de la transition'),
        ),
    ]
