# Generated by Django 3.1.3 on 2020-12-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irib', '0013_transition_occ'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30, verbose_name='Mot à POSER !')),
                ('missing_date', models.DateTimeField(auto_now=True, verbose_name='Date de la problématique')),
                ('fixed_date', models.DateTimeField(null=True, verbose_name='Date de maintenance')),
            ],
        ),
    ]
